id: sysprefs_time_machine_encrypted_configure
title: "Ensure Time Machine Volumes are Encrypted"
discussion: |
  Time Machine volumes _MUST_ be encrypted. 
check: |
  tmdestination=$(/usr/bin/tmutil destinationinfo 2>/dev/null | /usr/bin/awk -F': ' '/Name/{print $2}')
  if [[ "$tmdestination" = "" ]]; then
      echo "1"
  else
      tmVolMounted=$(/usr/sbin/diskutil info "${tmdestination}" 2>&1 | /usr/bin/awk '/Mounted/{print $2}')
      tmVolEncrypted=$(/usr/sbin/diskutil info "${tmdestination}" 2>&1 | /usr/bin/awk '/FileVault/{print $2}')

      if [[ "$tmVolMounted" = "Yes" && "$tmVolEncrypted" = "Yes" ]]; then
          echo "1"
      else
          if [[ "$tmVolMounted" = "" ]]; then
              echo "1"
          else
              echo "0"
          fi
      fi
  fi
result: 
  integer: 1
fix: |
  . Go to System Preferences -> Time Machine
  . Click *Select Disk*
  . Select existing Backup Disk under *Available Disks*
  . Click *Encrypt Backups*
  . Click *Use Disk*
references:
  cce:
    - N/A
  cci: 
    - N/A
  800-53r5:
    - N/A
  800-53r4: 
    - N/A
  srg:
    - N/A
  disa_stig: 
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark: 
      - 2.7.2 (level 2)
    v8:
      - 3.6
      - 3.11
      - 11.2
macOS:
  - "12.0"
tags:
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: