id: sysprefs_time_server_configure
title: "Configure macOS to Use an Authorized Time Server"
discussion: |
  Approved time servers _MUST_ be the only servers configured for use.

  This rule ensures the uniformity of time stamps for information systems with multiple system clocks and systems connected over a network.
check: |
    /usr/bin/osascript -l JavaScript << EOS
    ObjC.import('Foundation')
    ObjC.unwrap($.NSUserDefaults.alloc.initWithSuiteName('com.apple.MCX')\
    .objectForKey('timeServer'))
    EOS 
result:
  string: "time-a.nist.gov,time-b.nist.gov"
fix: |
  This is implemented by a Configuration Profile.
references:
  cce:
    - CCE-91080-2
  cci: 
    - CCI-001891
    - CCI-002046
  800-53r5:
    - AU-12(1)
    - SC-45(1)
  800-53r4: 
    - AU-8(1)
  srg:
    - N/A
  disa_stig: 
    - N/A
  800-171r2:
    - 3.3.7
  cisv8:
    - 8.4
macOS:
  - "12.0"
tags:
  - 800-171 
  - cnssi-1253 
  - 800-53r5_low 
  - 800-53r5_moderate 
  - 800-53r5_high 
  - 800-53r4_moderate 
  - 800-53r4_high
  - cisv8
severity: "medium"
mobileconfig: true
mobileconfig_info:
  com.apple.MCX:
    timeServer: "time-a.nist.gov,time-b.nist.gov"