id: os_install_log_retention_no_max_size_configure
title: "Configure Install.log Retention to Not Contain a Maximum File Size"
discussion: |
  The install log retention _MUST_ be configured to not contain a maximum file size.
check: |

result:
  integer: 0
fix: |
  [source,bash]
  ----
  sed -i.bak "s/\* file \/var\/log\/install.log.*/\* file \/var\/log\/install.log format='\$\(\(Time\)\(JZ\)\) \$Host \$\(Sender\)\[\$\(PID\\)\]: \$Message' rotate=utc compress file_max=50M ttl=365/g"
  ----  
references:
  cce:
    - N/A
  cci:
    - N/A
  800-53r5:
    - SI-11
  800-53r4:
    - SI-11
  srg:
    - N/A
  disa_stig:
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark:
      - 3.3 (level 1)
    v8:
      - 8.1
      - 8.3
macOS:
  - "12.0"
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
mobileconfig: false
mobileconfig_info: