id: os_time_limit_configure
title: "Ensure time set within "
discussion: |
  The macOS time synchronization daemon (timed) _MUST_ be enabled for proper time synchronization to an authorized time server.

  NOTE: The time synchronization daemon is enabled by default on macOS.
check: |
  /usr/bin/sntp $(/usr/sbin/systemsetup -getnetworktimeserver | /usr/bin/awk '{print $4}') | /usr/bin/awk -F'.' '/\+\/\-/{if (substr($1,2) >= 270) {print "No"} else {print "Yes"}}'
result:
  string: "Yes"
fix: |
  [source,bash]
  ----
  /usr/bin/sntp -Ss $(/usr/sbin/systemsetup -getnetworktimeserver | /usr/bin/awk '{print $4}')
  ----
references:
  cce:
    - N/A
  cci: 
    - N/A    
  800-53r5:
    - N/A
  800-53r4: 
    - N/A
  srg:
    - N/A
  disa_stig: 
    - N/A
  800-171r2:
    - N/A
  cis:
    benchmark:
      - 2.2.2 (level 1)
    v8:
      - 8.4
macOS:
  - "12.0"
tags:
  - cis_lvl1
  - cis_lvl2
  - cisv8
severity: "medium"
mobileconfig: false
mobileconfig_info:
